#!/bin/bash
# Open Gmail Web Compose tab directly in Google Chrome
case "$1" in
  1)
    echo "Opening Gmail compose for Prof. Weizhe Zhang (Harbin Institute of Tech (HIT)) in Google Chrome..."
    google-chrome "https://mail.google.com/mail/u/2/?view=cm&fs=1&tf=1&to=wzzhang%40hit.edu.cn&su=Prospective+MSc+Candidate+%28CSC+Scholarship+2026%2F2027%29+-+Fuad+Ahmed+%28Computer+Science%29&body=Dear+Professor+Weizhe+Zhang%2C%0A%0AI+hope+this+email+finds+you+well.%0A%0AMy+name+is+Fuad+Ahmed%2C+an+Ethiopian+Computer+Science+graduate+%28BSc%2C+St.+Mary%E2%80%99s+University%2C+Major+GPA%3A+3.20%2F4.00%29+and+Full-Stack+Software+Engineer+with+three+years+of+practical+experience+building+high-concurrency+systems+and+mobile+applications.%0A%0AI+have+been+studying+your+laboratory%E2%80%99s+research+at+the+Faculty+of+Computing+at+Harbin+Institute+of+Technology%2C+particularly+your+work+in+parallel+and+distributed+systems%2C+cloud+computing+architectures%2C+and+fault+tolerance.+%0A%0AMy+engineering+background+is+grounded+in+production+software+where+concurrency+and+data+integrity+are+critical%3A%0A1.+Concurrency+%26+Ledger+Integrity+%28LuckyDraw%29%3A+Architected+a+high-concurrency+transaction+and+lottery+engine+using+atomic+row-locking+%28DB%3A%3Atransaction+with+lockForUpdate%29+and+integer-cent+financial+ledger+arithmetic+to+eliminate+race+conditions+and+double-spending+risks.%0A2.+Geospatial+Mobile+Systems+%28Addis+Condo+Finder%29%3A+Engineered+a+crowdsourced+mapping+platform+with+Flutter+and+Laravel+REST+APIs%2C+implementing+viewport+spatial+indexing+and+offline-first+SQLite+local+synchronization.%0A3.+System+Lifecycle+Engineering%3A+Implemented+persistent+Android+background+services+and+IPC+routines+across+volatile+networks.%0A%0AI+am+applying+for+the+2026%2F2027+Master%E2%80%99s+Degree+in+Computer+Science+and+Technology+under+the+Chinese+Government+Scholarship+%28CSC+Type+B+-+High-Level+University+Program%29+or+HIT+Fellowship.+My+attached+research+proposal+investigates+%22Distributed+Cloud-Edge+Architectures+and+High-Concurrency+Transaction+Systems+for+Scalable+Mobile+Infrastructure.%22%0A%0AI+would+be+deeply+honored+to+pursue+my+Master%E2%80%99s+thesis+under+your+supervision+and+contribute+my+hands-on+systems+development+capabilities+to+your+ongoing+research+projects.%0A%0AAttached+please+find+my+CV%2C+Academic+Transcripts%2C+and+Research+Proposal.+My+open-source+code+can+be+reviewed+at%3A+https%3A%2F%2Fgithub.com%2Ffuad745%0A%0AIf+my+profile+aligns+with+your+laboratory%2C+would+you+be+willing+to+support+my+application+with+a+Provisional+Acceptance+Letter%3F%0A%0AThank+you+very+much+for+your+time%2C+guidance%2C+and+consideration.%0A%0ARespectfully+yours%2C%0A%0AFuad+Ahmed%0AAddis+Ababa%2C+Ethiopia%0AEmail%3A+fuadahmedt%40gmail.com+%7C+Phone%3A+%2B251+925+278+350%0AGitHub%3A+https%3A%2F%2Fgithub.com%2Ffuad745%0ALinkedIn%3A+https%3A%2F%2Flinkedin.com%2Fin%2Ffuad-ahmed-fullstack" &
    ;;
  2)
    echo "Opening Gmail compose for Assoc. Prof. Song Yang (Beijing Institute of Tech (BIT)) in Google Chrome..."
    google-chrome "https://mail.google.com/mail/u/2/?view=cm&fs=1&tf=1&to=S.Yang%40bit.edu.cn&su=Prospective+Master%27s+Student+%28CSC+%2F+BIT+Fellowship+2026%2F2027%29+-+Fuad+Ahmed&body=Dear+Professor+Song+Yang%2C%0A%0AI+hope+this+email+finds+you+well.%0A%0AMy+name+is+Fuad+Ahmed%2C+an+Ethiopian+Computer+Science+graduate+from+St.+Mary%E2%80%99s+University+%283.20+Major+GPA%29+and+Full-Stack+Software+Engineer.+I+am+writing+to+convey+my+keen+interest+in+pursuing+a+Master+of+Science+in+Computer+Science+and+Technology+at+Beijing+Institute+of+Technology+under+your+supervision.%0A%0AI+have+followed+your+research+on+cloud+and+edge+computing%2C+distributed+system+modeling%2C+and+network+resource+optimization.+My+practical+background+focuses+directly+on+the+challenges+of+edge-cloud+interaction+and+mobile+systems+in+developing+network+environments%3A%0A%E2%80%A2+Distributed+Geospatial+Systems%3A+Developed+Addis+Condo+Finder%2C+combining+mobile+clients+%28Flutter%29+with+RESTful+backend+services%2C+spatial+bounding-box+indexing%2C+and+client-side+SQLite+caching+for+offline+resilience.%0A%E2%80%A2+High-Concurrency+Ledger+Integrity%3A+Designed+atomic+transaction+systems+with+strict+row-level+isolation+and+integer-cent+arithmetic%2C+ensuring+zero+financial+drift+under+burst+traffic.%0A%E2%80%A2+Systems+Lifecycle+%26+IPC%3A+Implemented+persistent+Android+background+services+and+IPC+routines+across+volatile+cellular+networks.%0A%0AI+am+applying+for+the+2026%2F2027+academic+year+via+the+Chinese+Government+Scholarship+%28CSC+Type+B%29+and+BIT+Presidential+Fellowship.+My+proposed+research+topic+is+%22Distributed+Cloud-Edge+Architectures+and+High-Concurrency+Systems+for+Mobile+Infrastructure.%22%0A%0AI+would+be+deeply+privileged+to+contribute+my+full-stack+engineering+capabilities+to+your+research+group.%0A%0AAttached+please+find+my+CV%2C+Transcripts%2C+and+formal+Research+Proposal.+My+open-source+projects+can+be+inspected+at%3A+https%3A%2F%2Fgithub.com%2Ffuad745%0A%0AWould+you+be+willing+to+support+my+admission+and+scholarship+application+with+a+Provisional+Acceptance+Letter%3F%0A%0AThank+you+very+much+for+your+time+and+guidance.%0A%0ARespectfully+yours%2C%0A%0AFuad+Ahmed%0AAddis+Ababa%2C+Ethiopia%0AEmail%3A+fuadahmedt%40gmail.com+%7C+Phone%3A+%2B251+925+278+350" &
    ;;
  3)
    echo "Opening Gmail compose for Prof. Mingjun Xiao (Univ. of Science & Tech of China (USTC)) in Google Chrome..."
    google-chrome "https://mail.google.com/mail/u/2/?view=cm&fs=1&tf=1&to=xiaomj%40ustc.edu.cn&su=Prospective+MSc+Student+%28CSC+%2F+USTC+Fellowship+2026%2F2027%29+-+Fuad+Ahmed&body=Dear+Professor+Mingjun+Xiao%2C%0A%0AI+hope+this+email+finds+you+well.%0A%0AMy+name+is+Fuad+Ahmed%2C+an+Ethiopian+Computer+Science+graduate+%28BSc%2C+St.+Mary%E2%80%99s+University%2C+3.20+Major+GPA%29+and+Full-Stack+Software+Engineer.+I+am+writing+to+respectfully+express+my+interest+in+pursuing+a+Master+of+Science+in+Computer+Science+and+Technology+at+the+University+of+Science+and+Technology+of+China+%28USTC%29+under+your+mentorship.%0A%0AYour+laboratory%E2%80%99s+research+in+distributed+systems%2C+mobile+computing%2C+and+networked+algorithms+represents+the+exact+academic+direction+I+wish+to+pursue.+Over+the+last+three+years%2C+I+have+engineered+software+systems+that+bridge+mobile+frontends+with+robust+distributed+backends%3A%0A%E2%80%A2+Mobile+Edge+Architecture%3A+Developed+Addis+Condo+Finder+using+Flutter+and+Laravel%2C+implementing+viewport-based+bounding-box+queries+and+offline-first+local+synchronization+to+ensure+reliable+operation+under+intermittent+connectivity.%0A%E2%80%A2+Concurrency+Control%3A+Architected+transaction+engines+utilizing+atomic+row-locking+to+ensure+strict+consistency+and+prevent+race+conditions+during+burst+traffic.%0A%E2%80%A2+Production+Engineering%3A+Experienced+in+end-to-end+API+design%2C+relational+schema+indexing%2C+and+test-driven+validation.%0A%0AI+am+applying+for+the+2026%2F2027+academic+session+through+the+Chinese+Government+Scholarship+%28CSC+Type+B%29+and+the+USTC+Fellowship.+My+proposed+research+focuses+on+%22Distributed+Cloud-Edge+Architectures+and+High-Concurrency+Mobile+Infrastructure.%22%0A%0AI+would+be+deeply+honored+to+join+your+research+team+at+USTC+and+contribute+both+theoretical+dedication+and+practical+programming+abilities.%0A%0AAttached+please+find+my+CV%2C+Academic+Transcripts%2C+and+Research+Proposal.+My+public+repositories+can+be+reviewed+at%3A+https%3A%2F%2Fgithub.com%2Ffuad745%0A%0AIf+my+background+is+suitable+for+your+research+group%2C+would+you+be+willing+to+grant+me+a+Provisional+Acceptance+Letter%3F%0A%0AThank+you+very+much+for+your+time+and+consideration.%0A%0ARespectfully+yours%2C%0A%0AFuad+Ahmed%0AAddis+Ababa%2C+Ethiopia%0AEmail%3A+fuadahmedt%40gmail.com+%7C+Phone%3A+%2B251+925+278+350" &
    ;;
  4)
    echo "Opening Gmail compose for Prof. Shaohuai Shi (Harbin Institute of Tech (HIT)) in Google Chrome..."
    google-chrome "https://mail.google.com/mail/u/2/?view=cm&fs=1&tf=1&to=shaohuais%40hit.edu.cn&su=Prospective+Master%27s+Student+%28CSC+Type+B+2026%2F2027%29+-+Fuad+Ahmed+%28Distributed+Systems%29&body=Dear+Professor+Shaohuai+Shi%2C%0A%0AI+hope+you+are+having+a+productive+semester.%0A%0AMy+name+is+Fuad+Ahmed%2C+a+Computer+Science+graduate+from+St.+Mary%E2%80%99s+University+in+Addis+Ababa+%28Major+GPA%3A+3.20%2F4.00%29+and+Full-Stack+Software+Engineer.+I+am+writing+to+express+my+strong+interest+in+joining+your+research+team+at+Harbin+Institute+of+Technology+as+a+Master%E2%80%99s+candidate+for+the+2026%2F2027+academic+year.%0A%0AYour+pioneering+work+on+distributed+systems%2C+parallel+computing+frameworks%2C+and+computational+efficiency+strongly+resonates+with+my+background+in+backend+performance+optimization%3A%0A%E2%80%A2+Concurrency+%26+Deadlock+Avoidance%3A+Engineered+atomic+transaction+protocols+and+pessimistic+database+row-locks+%28lockForUpdate%29+for+high-frequency+financial+ledgers%2C+preventing+race+conditions+under+high+concurrency.%0A%E2%80%A2+Edge+%26+Mobile+Synchronization%3A+Built+offline-first+mobile+applications+with+client-side+caching+and+multi-user+consensus+verification+over+bandwidth-constrained+networks.%0A%E2%80%A2+Automated+Benchmarking%3A+Developed+automated+test+suites+validating+throughput%2C+deadlock+recovery%2C+and+HMAC+payload+security.%0A%0AI+intend+to+apply+for+the+Master%27s+Program+in+Computer+Science+and+Technology+through+the+Chinese+Government+Scholarship+%28CSC+Type+B%29+or+HIT+Scholarship.+I+have+prepared+an+extensive+study+proposal+focused+on+distributed+architectures+and+high-concurrency+mobile+systems.%0A%0AI+would+be+thrilled+to+bring+my+practical+programming+skills+%28Flutter%2FDart%2C+Laravel%2C+MySQL%2C+REST+APIs%2C+Git%29+to+your+laboratory.%0A%0AMy+CV%2C+Academic+Transcripts%2C+and+Research+Proposal+are+attached.+My+public+GitHub+repositories+are+available+at%3A+https%3A%2F%2Fgithub.com%2Ffuad745%0A%0ACould+you+please+consider+accepting+me+as+an+MSc+student+under+your+guidance%3F+If+your+evaluation+is+favorable%2C+I+would+be+grateful+if+you+could+issue+a+Provisional+Acceptance+Letter+to+support+my+scholarship+dossier.%0A%0AThank+you+very+much+for+your+consideration.%0A%0ASincerely%2C%0A%0AFuad+Ahmed%0AEmail%3A+fuadahmedt%40gmail.com+%7C+Tel%3A+%2B251+925+278+350%0AAddis+Ababa%2C+Ethiopia" &
    ;;
  5)
    echo "Opening Gmail compose for Prof. Meihui Zhang (Beijing Institute of Tech (BIT)) in Google Chrome..."
    google-chrome "https://mail.google.com/mail/u/2/?view=cm&fs=1&tf=1&to=meihui_zhang%40bit.edu.cn&su=Prospective+MSc+Candidate+%28CSC+Type+B+2026%2F2027%29+-+Fuad+Ahmed+%28Database+Systems%29&body=Dear+Professor+Meihui+Zhang%2C%0A%0AI+hope+you+are+having+a+pleasant+week.%0A%0AMy+name+is+Fuad+Ahmed%2C+a+Computer+Science+graduate+from+St.+Mary%E2%80%99s+University+in+Addis+Ababa+%28Major+GPA%3A+3.20%2F4.00%29+and+Full-Stack+Software+Engineer.+I+am+writing+to+express+my+earnest+enthusiasm+for+joining+your+research+laboratory+at+Beijing+Institute+of+Technology+as+a+Master%E2%80%99s+candidate+for+2026%2F2027.%0A%0AYour+distinguished+work+on+big+data+management%2C+distributed+database+systems%2C+and+transaction+verification+directly+aligns+with+my+core+technical+interests%3A%0A%E2%80%A2+Transaction+Semantics+%26+Concurrency%3A+Built+a+high-volume+financial+ledger+and+lottery+engine+enforcing+strict+ACID+compliance+through+pessimistic+row-locking+%28lockForUpdate%29+and+atomic+transaction+boundaries+to+eliminate+race+conditions.%0A%E2%80%A2+Interdisciplinary+Foundations%3A+Completed+certified+training+in+Capital+Markets+and+Securities+Analysis+at+the+Addis+Ababa+University+School+of+Commerce%2C+reinforcing+the+mathematical+and+structural+rigor+demanded+by+financial+and+ledger+architectures.%0A%E2%80%A2+Data+Indexing+%26+Query+Optimization%3A+Implemented+spatial+queries+and+local+SQLite+persistence+for+high-throughput+mobile+applications.%0A%0AI+am+preparing+my+application+for+the+Master%27s+in+Computer+Science+and+Technology+under+the+Chinese+Government+Scholarship+%28CSC+Type+B%29+and+BIT+Fellowship.%0A%0AI+am+eager+to+contribute+my+hands-on+software+development+skills+to+your+laboratory%27s+ongoing+distributed+data+projects.%0A%0AAttached+are+my+Academic+CV%2C+Transcripts%2C+and+Research+Proposal.+My+code+repositories+are+publicly+available+at%3A+https%3A%2F%2Fgithub.com%2Ffuad745%0A%0ACould+you+please+consider+accepting+me+as+a+Master%27s+student+under+your+mentorship%3F+If+my+profile+meets+your+standards%2C+I+would+be+grateful+for+a+Provisional+Acceptance+Letter+to+accompany+my+application.%0A%0AThank+you+very+much+for+your+consideration.%0A%0AWarm+regards%2C%0A%0AFuad+Ahmed%0AEmail%3A+fuadahmedt%40gmail.com+%7C+Tel%3A+%2B251+925+278+350%0AAddis+Ababa%2C+Ethiopia" &
    ;;
  6)
    echo "Opening Gmail compose for Prof. Gongming Zhao (Univ. of Science & Tech of China (USTC)) in Google Chrome..."
    google-chrome "https://mail.google.com/mail/u/2/?view=cm&fs=1&tf=1&to=gmzhao%40ustc.edu.cn&su=Prospective+Master%27s+Candidate+%28CSC+Type+B+2026%2F2027%29+-+Fuad+Ahmed&body=Dear+Professor+Gongming+Zhao%2C%0A%0AI+hope+you+are+having+a+productive+week.%0A%0AMy+name+is+Fuad+Ahmed%2C+a+Computer+Science+graduate+from+St.+Mary%E2%80%99s+University+in+Addis+Ababa+%28Major+GPA%3A+3.20%2F4.00%29+and+Full-Stack+Software+Engineer.+I+am+writing+to+express+my+strong+interest+in+joining+your+research+laboratory+at+USTC+as+an+MSc+student+for+the+2026%2F2027+academic+year.%0A%0AYour+laboratory%E2%80%99s+work+in+cloud+computing%2C+distributed+systems%2C+and+networked+systems+optimization+strongly+aligns+with+my+practical+software+engineering+background%3A%0A%E2%80%A2+High-Throughput+Concurrency%3A+Built+transaction+processing+services+enforcing+atomic+row-locks+and+integer-cent+ledger+arithmetic+to+eliminate+race+conditions+and+financial+drift+under+heavy+loads.%0A%E2%80%A2+Scalable+Systems+Engineering%3A+Designed+RESTful+API+backends%2C+event-driven+queues%2C+and+automated+test+suites+for+deadlock+resilience+and+throughput+benchmarking.%0A%E2%80%A2+Mobile+%26+Distributed+Caching%3A+Implemented+offline-first+caching+and+synchronization+protocols+for+mobile+clients+across+high-latency+networks.%0A%0AI+am+applying+through+the+Chinese+Government+Scholarship+%28CSC+Type+B%29+and+USTC+Fellowship.+I+have+developed+a+detailed+research+proposal+on+distributed+cloud-edge+systems+and+concurrency+control.%0A%0AI+am+enthusiastic+about+the+prospect+of+contributing+to+your+research+projects+and+learning+under+your+supervision+at+USTC.%0A%0AMy+CV%2C+Academic+Transcripts%2C+and+Research+Proposal+are+attached+for+your+consideration.+My+public+code+can+be+reviewed+at%3A+https%3A%2F%2Fgithub.com%2Ffuad745%0A%0ACould+you+please+consider+accepting+me+as+a+Master%27s+student+in+your+group%3F+If+favorable%2C+a+Provisional+Acceptance+Letter+from+you+would+greatly+strengthen+my+scholarship+nomination.%0A%0AThank+you+very+much+for+your+guidance+and+consideration.%0A%0ASincerely%2C%0A%0AFuad+Ahmed%0Afuadahmedt%40gmail.com+%7C+%2B251+925+278+350%0AAddis+Ababa%2C+Ethiopia" &
    ;;
  *)
    echo "Usage: ./open_gmail_compose.sh <1-6>"
    echo "  1: Prof. Weizhe Zhang (HIT - Distributed Systems)"
    echo "  2: Assoc. Prof. Song Yang (BIT - Cloud & Edge)"
    echo "  3: Prof. Mingjun Xiao (USTC - Mobile & Distributed)"
    echo "  4: Prof. Shaohuai Shi (HIT - Distributed ML)"
    echo "  5: Prof. Meihui Zhang (BIT - Distributed Databases)"
    echo "  6: Prof. Gongming Zhao (USTC - Cloud Networks)"
    ;;
esac
